routes/web.php
<?php

Route::group(['namespace' => 'Parking', 'prefix' => 'parking'], function (){
    Route::resource('customers', 'CustomerController', ['except'=> ['show']])->names('parking.customers');
    Route::get('/customers/{id}/destroy/', 'CustomerController@destroy')->name('parking.customers.destroy');
    Route::get('/customers/{id}/destroy/car/{car_id}', 'CustomerController@destroyCar')->name('parking.customers.destroy.car');
    Route::resource('cars', 'CarController')->only(['index', 'update'])->names('parking.cars');
    Route::get('/cars/parked/', 'CarController@parkedCars')->name('parking.cars.parked');
    Route::get('/park-cars/', 'ParkingController@parkCars')->name('parking.park.cars');
    Route::patch('/park-cars/', 'ParkingController@parkCarsUpdate')->name('parking.park.cars.update');
    Route::get('/cars/{id}/get_in', 'CarController@getIn')->name('parking.cars.get_in');
    Route::get('/cars/{id}/get_out', 'CarController@getOut')->name('parking.cars.get_out');
});

Route::get('', 'Parking\ParkingController@start')->name('parking.start');

app/Models/Parking/Car.php
<?php

namespace App\Models\Parking;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\MessageBag;

class Car extends Model
{
    public static function validate($car)
    {
        $errors = new MessageBag();

        //Проверить наличие лишних полей
        if (!empty(array_diff(array_keys($car), self::getFields()))) {
            return $errors->add('msg',
                sprintf('Присуствуют лишние поля у автомобиля %s', $car['car_number'])
            );
        }

        //Проверить наличие обязательных полей
        if (!empty(array_diff(self::getRequiredFields(), array_keys($car)))) {
            return $errors->add('msg',
                sprintf('Заполните обязательные поля у автомобиля %s', $car['car_number'])
            );
        }

        if (!in_array((int)$car['is_parked'], [0, 1])) {
            $errors->add('msg',
                sprintf('Поле %s соддержит недопустимое значение у автомобиля %s',
                    self::getFieldTitle('is_parked'),
                    $car['car_number'])
            );
        }

        if (!in_array(mb_strlen($car['car_number']), [8, 9])
            || !preg_match('/[а-яА-Я][0-9]{3}[а-яА-Я]{2}[0-9]{2,3}$/msiu', $car['car_number'])) {
            return $errors->add('msg', sprintf('Неправильно заполнен %s', self::getFieldTitle('car_number')));
        }

        if (isset($car['id']) && is_numeric($car['id']) && $car['id'] > 0) {
            $dbCar = DB::table('cars')
                ->where('id', $car['id'])
                ->first();
            if (!$dbCar) {
                return $errors->add('msg', sprintf('Автомобиль с id %d не найден', $car['id']));
            }

            if (($dbCar->car_number != $car['car_number'] && self::doesCarNumberExist($car['car_number']))) {
                return $errors->add('msg', sprintf('Автомобиль с номером %s уже существует', $car['car_number']));
            }

        } elseif (self::doesCarNumberExist($car['car_number'])) {
            return $errors->add('msg', sprintf('Автомобиль с номером %s уже существует', $car['car_number']));
        }

        return $errors;
    }

    public static function updateIsParked($id, int $isParked)
    {
        $errors = new MessageBag();

        $doesCarExist = DB::table('cars')
                ->where('id', $id)
                ->count() == 1;

        if (!$doesCarExist) {
            return $errors->add('msg', sprintf('Автомобиль с id %d не найден', $id));
        }

        DB::table('cars')
            ->where('id', $id)
            ->update(array('is_parked' => $isParked));

        return $errors;
    }

    public static function doesCarNumberExist($carNumber)
    {
        $doesCarNumberExist = DB::table('cars')
                ->where('car_number', $carNumber)
                ->count() > 0;

        return $doesCarNumberExist;
    }

    public static function getFieldTitles()
    {
        return array(
            'id' => 'ID',
            'marque' => 'марка',
            'model' => 'модель',
            'color' => 'цвет',
            'car_number' => 'гос. номер',
            'is_parked' => 'припаркована',
        );
    }

    public static function getFieldTitle($title)
    {
        return self::getFieldTitles()[$title];
    }

    public static function getFields()
    {
        return array(
            'id',
            'marque',
            'model',
            'color',
            'car_number',
            'customer_id',
            'is_parked',
        );
    }

    public static function getRequiredFields()
    {
        return array(
            'marque',
            'model',
            'color',
            'car_number',
            'customer_id',
            'is_parked',
        );
    }
}

app/Http/Controllers/Parking/CarController.php
<?php

namespace App\Http\Controllers\Parking;

use App\Http\Controllers\Controller;
use App\Models\Parking\Car;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\MessageBag;

class CarController extends Controller
{
    const ITEMS_PER_PAGE = 10;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = DB::table('customers')
            ->join('cars', 'cars.customer_id', '=', 'customers.id')
            ->paginate(self::ITEMS_PER_PAGE);

        return view('Parking.cars', compact('paginator'));
    }

    /**
     * Display a listing of the parked cars.
     *
     * @return \Illuminate\Http\Response
     */
    public function parkedCars()
    {
        $paginator = DB::table('cars')
            ->where('is_parked', '=', 1)
            ->addSelect(DB::raw('COUNT(*) as car_count'))
            ->addSelect(array('marque', 'model'))
            ->groupBy(array('marque', 'model'))
            ->paginate(self::ITEMS_PER_PAGE);

        return view('Parking.parked_cars', compact('paginator'));
    }

    /**
     * Update the specified resources in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $cars = $request->input('cars');

        foreach ($cars as $index => $car) {
            $cars[$index]['is_parked'] = (isset($car['is_parked']) && $car['is_parked'] === 'on') ? 1 : 0;
        }

        $errors = new MessageBag();
        foreach ($cars as $car) {
            $errors->merge(Car::validate($car));
        }

        if ($errors->any()) {
            return back()->withErrors(['msg' => $errors->all()])
                ->withInput($request->input());
        }

        $newCars = array();

        foreach ($cars as $car) {
            if (preg_match('/n[0-9]+/', $car['id'])) {
                unset($car['id']);
                $newCars[] = $car;
                continue;
            }

            $carId = $car['id'];
            unset($car['id']);

            DB::table('cars')
                ->where('id', $carId)
                ->update($car);
        }

        if (!empty($newCars)) {
            DB::table('cars')
                ->insert($newCars);
        }

        return back()->withInput($request->input());
    }

    /**
     * Set is_parked = 1
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function getIn($id)
    {
        $errors = Car::updateIsParked($id, 1);
        return back()->withErrors(['msg' => $errors->all()]);
    }

    /**
     * Set is_parked = 0
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function getOut($id)
    {
        $errors = Car::updateIsParked($id, 0);
        return back()->withErrors(['msg' => $errors->all()]);
    }
}

app/Http/Controllers/Parking/CustomerController.php
<?php

namespace App\Http\Controllers\Parking;

use App\Http\Controllers\Controller;
use App\Models\Parking\Car;
use App\Models\Parking\Customer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\MessageBag;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class CustomerController extends Controller
{
    const ITEMS_PER_PAGE = 10;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = DB::table('customers')
            ->join('cars', 'cars.customer_id', '=', 'customers.id')
            ->addSelect(DB::raw('COUNT(*) as car_count'))
            ->addSelect('customers.*')
            ->groupBy('customers.id')
            ->paginate(self::ITEMS_PER_PAGE);


        return view('Parking.customers', compact('paginator'));
    }

    /**
     * Show the form for creating a new customer.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Parking.customer_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $customer = $request->input('customer');
        $cars = $request->input('cars');
        $customer['phone'] = preg_replace('/[^0-9]/', '', $customer['phone']);

        $errors = new MessageBag();

        if(empty($cars) || count($cars) < 1){
            $errors->add('msg', 'У клиента должна быть хотя бы одна машина');
            $customer = (object)$customer;
            return view('Parking.customer_create', compact('customer', 'errors'));
        }

        $errors->merge(Customer::validate($customer));

        $carNumbers = array_column($cars, 'car_number');

        if (count($carNumbers) != count(array_unique($carNumbers))) {
            $errors->add('msg', 'Номера машин должны быть уникальны');
        }

        foreach ($cars as $index => $car) {
            $cars[$index]['is_parked'] = (isset($car['is_parked']) && $car['is_parked'] === 'on') ? 1 : 0;
        }

        foreach ($cars as $car) {
            $errors->merge(Car::validate($car));
        }

        if ($errors->any()) {
            $customer = (object)$customer;
            $customer->cars = array_map(
                function ($car) {
                    return (object)$car;
                },
                $cars
            );

            return view('Parking.customer_create', compact('customer', 'errors'));
        }

        $id = DB::table('customers')
            ->insertGetId($customer);

        foreach ($cars as $index => $car) {
            $cars[$index]['customer_id'] = $id;
            unset($cars[$index]['id']);
        }

        unset($customer['id']);
        DB::table('cars')
            ->insert($cars);

        return redirect(route('parking.customers.edit', array($id)));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = DB::table('customers')
            ->where('id', $id)
            ->first();

        if (!$customer) {
            throw new NotFoundHttpException();
        }

        $cars = DB::table('cars')
            ->where('customer_id', $id)
            ->get();
        $customer->cars = $cars;
        return view('Parking.customer_edit', compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $customer = $request->input('customer');
        $customer['phone'] = preg_replace('/[^0-9]/', '', $customer['phone']);

        $errors = Customer::validate($customer);

        if ($errors->any()) {
            return back()->withErrors(['msg' => $errors->all()]);
        }

        unset($customer['id']);

        DB::table('customers')
            ->where('id', $id)
            ->update($customer);

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customer = DB::table('customers')
            ->where('id', $id)
            ->first();

        if (!$customer) {
            throw new NotFoundHttpException();
        }

        DB::table('customers')
            ->where('id', $id)
            ->delete();

        return redirect(route('parking.customers.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @param int $carId
     * @return \Illuminate\Http\Response
     */
    public function destroyCar(Request $request, $id, $carId)
    {
        $car = DB::table('cars')
            ->where('id', $carId)
            ->first();

        if (!$car || $car->customer_id != $id) {
            throw new NotFoundHttpException();
        }

        $countCars = DB::table('cars')
            ->where('customer_id', $id)
            ->count();

        if ($countCars <= 1) {
            DB::table('customers')
                ->where('id', $id)
                ->delete();
        }

        DB::table('cars')
            ->where('id', $carId)
            ->delete();

        return back();
    }
}

app/Http/Controllers/Parking/ParkingController.php
<?php

namespace App\Http\Controllers\Parking;

use App\Http\Controllers\Controller;
use App\Models\Parking\Car;
use App\Models\Parking\Customer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\MessageBag;

class ParkingController extends Controller
{
    /**
     * Display start page
     *
     * @return \Illuminate\Http\Response
     */
    public function start()
    {
        return view('Parking.start');
    }

    public static function parkCars(Request $request)
    {
        {
            $cars = DB::table('customers')
                ->join('cars', 'cars.customer_id', '=', 'customers.id')
                ->where('cars.is_parked', '=', 0)
                ->get()->toArray();

            if(empty($cars)){
                return view('Parking.park_cars');
            }

            $customers = array();

            foreach ($cars as $car) {
                $car = (array)$car;
                if (!isset($customers[$car['customer_id']])) {
                    foreach (Customer::getFields() as $customerField) {
                        $customers[$car['customer_id']][$customerField] = $car[$customerField];
                    }
                    $customers[$car['customer_id']]['id'] = $car['customer_id'];
                    $customers[$car['customer_id']]['cars'] = array();
                }

                foreach (Car::getFields() as $carField) {
                    $customers[$car['customer_id']]['cars'][$car['id']][$carField] = $car[$carField];
                }
            }

            $customers = array_map(
                function ($customer) {
                    $customer['cars'] = array_map(
                        function ($car) {
                            return (object)$car;
                        },
                        $customer['cars']
                    );
                    return (object)$customer;
                },
                $customers
            );

            return view('Parking.park_cars', compact('customers'));
        }
    }

    public static function parkCarsUpdate(Request $request)
    {
        $customerId = $request->input('customer');
        $carIdList = $request->input('cars');

        if(empty($customerId)){
            return back()->withErrors(['msg' => 'Не заполнено id клиента']);
        }

        if(empty($carIdList)){
            return back()->withErrors(['msg' => 'Не выбраны автомобили']);
        }

        $doesCustomerExist = DB::table('customers')
            ->where('id', $customerId)
            ->count() === 1;

        if(!$doesCustomerExist){
            return back()->withErrors(['msg' => sprintf('Клиент с id %d не найден', $customerId)]);
        }

        $doCarsExist = DB::table('cars')
                ->whereIn('id', $carIdList)
                ->count() === count($carIdList);

        if(!$doCarsExist){
            return back()->withErrors(['msg' => 'Не все автомобили существуют']);
        }

        DB::table('cars')
            ->whereIn('id', $carIdList)
            ->update(array('is_parked' => 1));

        return back();
    }
}

resources/views/Parking/customer_create.blade.php
@extends('Parking.layouts.app')

@section('content')
    <div class="container parking">
        <div class="row">
            <div class="col-12 text-center">
                <h1>Новый клиент</h1>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-1">
                <a href="{{route('parking.start')}}" class="btn btn-primary">Главная</a>
            </div>
            <div class="col-1">
                <a href="{{route('parking.customers.index')}}" role="button" class="btn btn-primary">Клиенты</a>
            </div>
        </div>

        @if($errors->any())
            <div class="row">
                <div class="col-12 text-center">
                    @foreach($errors->all() as $error)
                        <div class="alert alert-danger" role="alert">
                            {{$error}}
                        </div>
                    @endforeach
                </div>
            </div>
        @endif

        <div class="row justify-content-center">

            <div class="col-12">
                <form method="POST" action="{{ route('parking.customers.store') }}">
                    @csrf
                    @include('Parking.includes.customer')

                    <div class="form-row mb-4">
                        <div class="col-6">
                            <h2>Автомобили</h2>
                            <div class="alert alert-warning" role="alert">
                                Укажите как минимум 1 автомобиль
                            </div>
                        </div>
                    </div>

                    <div id="cars">

                        @if(!empty($customer->cars))
                            @foreach ($customer->cars as $car)
                                @include('Parking.includes.car')
                            @endforeach
                        @endif

                        @php unset($car) @endphp

                        <div class="btn btn-primary" id="add-car">Добавить автомобиль</div>

                        <div class="container">
                            <div class="row mt-5 mb-5">
                                <div class="col-3">
                                    <button type="submit" class="btn btn-success">Сохранить</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="d-none" id="car-content">
                    @include('Parking.includes.car')
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    @include('Parking.includes.parking_scripts')

    @if(empty($customer->cars))
        <script>
            $(document).ready(addCar);
        </script>
    @endif
@endsection

resources/views/Parking/customer_edit.blade.php
@extends('Parking.layouts.app')

@section('content')

    <div class="container parking">
        <div class="row">
            <div class="col-12 text-center">
                <h1>Клиент</h1>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-1">
                <a href="{{route('parking.start')}}" class="btn btn-primary">Главная</a>
            </div>
            <div class="col-1">
                <a href="{{route('parking.customers.index')}}" role="button" class="btn btn-primary">Клиенты</a>
            </div>
        </div>

        @if($errors->any())
            <div class="row">
                <div class="col-12 text-center">
                    @foreach($errors->all() as $error)
                        <div class="alert alert-danger" role="alert">
                            {{$error}}
                        </div>
                    @endforeach
                </div>
            </div>
        @endif

        <div class="row justify-content-center">

            <div class="col-12">
                <form method="POST" action="{{ route('parking.customers.update', array($customer->id)) }}">
                    @method('PATCH')
                    @csrf
                    @include('Parking.includes.customer')
                    <div class="container">
                        <div class="row mt-5 mb-5">
                            <div class="col-4">
                                <button type="submit" class="btn btn-success">Сохранить</button>
                                <a href="{{ route('parking.customers.destroy', array($customer->id)) }}"
                                   class="btn btn-danger ml-4">Удалить</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row justify-content-center" id="cars">

            <div class="col-12">
                <form method="POST" action="{{ route('parking.cars.update', array($customer->id)) }}">
                    @method('PATCH')
                    @csrf
                    <div class="form-row mb-4">
                        <div class="col-6">
                            <h2>Автомобили</h2>
                            <div class="alert alert-warning" role="alert">
                                Укажите как минимум 1 автомобиль
                            </div>
                        </div>
                    </div>

                    @foreach ($customer->cars as $car)
                        @include('Parking.includes.car')
                    @endforeach

                    @php
                        unset($car);
                    @endphp

                    <div class="btn btn-primary" id="add-car">Добавить автомобиль</div>

                    <div class="container">
                        <div class="row mt-5 mb-5">
                            <div class="col-3">
                                <button type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="d-none" id="car-content">
                    @include('Parking.includes.car')
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    @include('Parking.includes.parking_scripts')
@endsection

resources/views/Parking/customers.blade.php
@extends('Parking.layouts.app')

@section('content')
    <div class="container parking">
        <div class="row">
            <div class="col-12 text-center">
                <h1>Все клиенты</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-1">
                <a href="{{route('parking.start')}}" class="btn btn-primary">Главная</a>
            </div>
            <div class="col-2">
                <a href="{{route('parking.customers.create')}}" class="btn btn-success">Добавить клиента</a>
            </div>
        </div>

        <div class="row">
            <div class="col-12 customers">
                <table class="table table-bordered table-hover">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Имя</th>
                        <th scope="col">Пол</th>
                        <th scope="col">Количество автомобилей</th>
                        <th scope="col">Телефон</th>
                        <th scope="col">Адрес</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($paginator as $customer)
                        <tr>
                            <td>{{$customer->id}}</td>
                            <td>{{implode(' ', array($customer->surname, $customer->name, $customer->last_name))}}</td>
                            <td>{{($customer->is_male === 1) ? 'Мужской' : 'Женский'}}</td>
                            <td>{{$customer->car_count}}</td>
                            <td>{{$customer->phone}}</td>
                            <td>{{$customer->address}}</td>
                            <td class="action-cell">
                                <div>
                                    <a href="{{route('parking.customers.edit', array($customer->id))}}"
                                       class="glyphicon glyphicon-pencil edit-row"></a>
                                </div>
                            </td>
                            <td class="action-cell">
                                <div>
                                    <a href="{{route('parking.customers.destroy', array($customer->id))}}"
                                       class="glyphicon glyphicon-remove remove-row" data-action="delete"></a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        @if($paginator->total() > $paginator->count())
            <div class="row justify-content-center">
                <div class="col-12">
                    {{ $paginator->links() }}
                </div>
            </div>
        @endif
    </div>

@endsection

resources/views/Parking/park_cars.blade.php
@extends('Parking.layouts.app')

@section('content')

    <div class="container parking">
        <div class="row mb-5">
            <div class="col-12 text-center">
                <h1>Добавить машину на автостоянку</h1>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-1">
                <a href="{{route('parking.start')}}" class="btn btn-primary">Главная</a>
            </div>
            <div class="col-2">
                <a href="{{route('parking.cars.index')}}" class="btn btn-primary">Все автомобили</a>
            </div>
            <div class="col-3">
                <a href="{{route('parking.cars.parked')}}" class="btn btn-primary">Автомобили на стоянке</a>
            </div>
        </div>

        @if($errors->any())
            <div class="row">
                <div class="col-12 text-center">
                    @foreach($errors->all() as $error)
                        <div class="alert alert-danger" role="alert">
                            {{$error}}
                        </div>
                    @endforeach
                </div>
            </div>
        @endif

        <div class="row justify-content-center">
            <div class="col-12">
                @if(isset($customers))
                    <form method="POST" action="{{ route('parking.park.cars.update')}}">
                        @method('PATCH')
                        @csrf

                        <div class="form-group">
                            <label for="customer">Клиенты</label>
                            <select class="form-control" id="customer-select" name="customer">
                                @php
                                    $allCustomers = $customers;
                                    $firstCustomer = array_shift($customers);
                                @endphp
                                <option value="{{$firstCustomer->id}}" selected="selected">
                                    {{implode(' ', array($firstCustomer->surname, $firstCustomer->name, $firstCustomer->last_name))}}
                                </option>
                                @foreach($customers as $customer)
                                    <option value="{{$customer->id}}">
                                        {{implode(' ', array($customer->surname, $customer->name, $customer->last_name))}}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="customer">Автомобили</label>
                            <select class="form-control" id="cars-select" name="cars[]" multiple>
                                @foreach($firstCustomer->cars as $car)
                                    <option value="{{$car->id}}">
                                        {{implode(' ', array($car->marque, $car->model, $car->color, $car->car_number))}}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                @else
                    <div class="alert alert-info" role="alert">
                        Все автомобили припаркованы
                    </div>
                @endif
            </div>
        </div>
    </div>

@endsection

@section('scripts')
   @if(isset($customers))
       <script>
           function updateCarsSelector(customerId) {
               $('#cars-select').empty();
               for (let carId in Customers[customerId]['cars']) {
                   if (!Customers[customerId]['cars'].hasOwnProperty(carId)) {
                       return;
                   }
                   let car = Customers[customerId]['cars'][carId];

                   addCarOption(car);
               }
           }

           function addCarOption(car) {
               let carOption = document.createElement('option');
               carOption.text = [car.marque, car.model, car.color, car.car_number].join(' ');
               carOption.value = car.id;

               $('#cars-select').append(carOption);
           }

           window.Customers = @json($allCustomers);

           $(document).ready(function () {
               $('#customer-select').change(function () {
                   let customerId = $(this).val();
                   updateCarsSelector(customerId);
               });
           });
       </script>
    @endif
@endsection

resources/views/Parking/start.blade.php
@extends('Parking.layouts.app')

@section('content')
    <div class="main">
        <h1>Система учёта клиентов автостоянки</h1>
        <div class="container">
            <div class="row justify-content-center mt-5">
                <div class="col-1">
                    <a href="{{route('parking.customers.index')}}" role="button" class="btn btn-primary">Клиенты</a>
                </div>
                <div class="col-1">
                    <a href="{{route('parking.cars.index')}}" role="button" class="btn btn-primary">Автомобили</a>
                </div>
            </div>
        </div>
    </div>
@endsection